baseURL = 'https://fradamroyal.com/'
languageCode = 'en-us'
title = 'Homilies & Thoughts'
theme = 'latex_fradamroyal'
pagination.pagerSize = 3
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
  mainSections = ['reflections', 'homilies']
  [params.author]
    name = "Rev. Adam Royal"
    abstract = """
    A collection of homilies and reflections to, hopefully, inspire and guide your faith.
    """
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Homilies'
    pageRef = '/homilies'
    weight = 20
  [[menus.main]]
    name = 'Reflections'
    pageRef = '/reflections'
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
