baseURL = 'https://fradamroyal.com/'
locale = 'en-us'
title = 'Homilies & Thoughts'
theme = 'latex_fradamroyal'
pagination.pagerSize = 12
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableRobotsTXT = true
enableGitInfo = true

[frontmatter]
  lastmod = ['lastmod', ':git', 'date', 'publishDate']

[params]
  description = "A collection of homilies and reflections to, hopefully, inspire and guide your faith."
  mainSections = ['reflections', 'homilies']
  [params.author]
    name = "Adam Royal"
    display_name = "Rev. Adam Royal"
    honorific_prefix = "Rev."
    url = "/about/"
  [params.license]
    name = "CC BY-SA 4.0"
    url = "https://creativecommons.org/licenses/by-sa/4.0/"
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Homilies'
    pageRef = '/homilies'
    weight = 20
  [[menus.main]]
    name = 'Reflections'
    pageRef = '/reflections'
    weight = 30
  [[menus.main]]
    name = 'Tools'
    pageRef = '/tools'
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.renderer]
    unsafe = true
