name = 'LaTeX'
license = 'MIT'
licenselink = 'LICENSE'
description = 'LaTeX inspired Hugo theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/fradamroyal/fradamroyal_com'


# If the theme has a single author
[author]
  name = 'Adam Royal'
  homepage = 'https://fradamroyal.com'

# If porting an existing theme
[original]
  author = 'kaisugi'
  homepage = 'https://github.com/kaisugi/'
  demosite = 'https://hugotex.vercel.app/'
  repo = 'https://github.com/kaisugi/HugoTeX'
